### General project setup
general:
  inferBuildTool: true
  gitHttpsCredentialsId: "CTM_token"

### Step-specific configuration
steps:
  mavenExecute:
    dockerImage: devxci/mbtci:1.0.14

  artifactPrepareVersion:
    versioningType: cloud_noTag

### Stage-specific configuration
stages:
  "Confirm":
    manualConfirmation: false

#  Integration:
#    credentials:
#      - alias: 'mySystemAlias'
#        credentialId: 'mySystemCredentialsId'

Release:
  cfTargets:
    - org: "sna-common-dev"
      space: "IS-DEV"
      apiEndpoint: "https://api.cf.us20.hana.ondemand.com"
      appName: "SNAH_Common_Notifications"
      manifest: "manifest.yml"
      credentialsId: "deploy-to-cf"
